owner: routechoices
repo: upptime

sites:
  - name: Website
    url: https://www.routechoices.com/
  - name: API
    url: https://api.routechoices.com/healthcheck/?format=json
  - name: WMS Tile Server
    url: https://wms.routechoices.com/?service=WMS&request=GetMap&layers=fhDbzlQSLho&styles=&format=image%2Fjpeg&transparent=false&version=1.1.1&width=512&height=512&srs=EPSG%3A3857&bbox=2641663.6975356913,8727274.141488286,2661231.576776697,8746842.020729292
  - name: TCP Server
    url: routechoices.com
    port: 5004
    check: "tcp-ping"

status-website:
  cname: status.routechoices.com
  logoUrl: https://cdn.routechoic.es/icon-512.png
  name: Routechoices.com status
  introTitle: "**Routechoices** is an easy-to-use yet powerful live GPS tracking platform designed for orienteering and outdoor sports enthusiasts."
  introMessage: This page show you in **real-time** the status of our online services
  navbar:
    - title: Status
      href: /
    - title: Home
      href: https://www.routechoices.com
